// Glyphs.generated.swift
// GENERATED by tools/glyphs/extract_glyphs.py — do not hand-edit.
//
// Real human pen-stroke exemplars from the MathWriting dataset
// (Google Research), CC BY-NC-SA 4.0 license:
// https://creativecommons.org/licenses/by-nc-sa/4.0/
// Source: https://storage.googleapis.com/mathwriting_data/mathwriting-2024-excerpt.tgz
// Fine for this demo; flag for any product future (NC clause).
//
// Per-symbol source (dataset exemplar vs hand-authored fallback for
// symbols absent from the ~1.5MB excerpt sample):
//   0          dataset:train:050eb35c2f18a695:[16]
//   1          dataset:train:0050464363a7d02d:[6]
//   2          dataset:symbols:010b76fd723a3af2.inkml
//   3          dataset:symbols:013433c6b018d0e2.inkml
//   4          hand-authored
//   5          hand-authored
//   6          hand-authored
//   7          hand-authored
//   8          hand-authored
//   9          hand-authored
//   x          hand-authored
//   y          hand-authored
//   +          dataset:train:050eb35c2f18a695:[4, 5]
//   -          hand-authored
//   =          dataset:train:0050464363a7d02d:[1, 2]
//   (          dataset:symbols:012994d2a88b84a4.inkml
//   )          dataset:symbols:02c3a6a126b713c4.inkml
//   .          hand-authored
//   /          dataset:train:049d2cf3f10ac2d7:[17]
//   plusminus  dataset:train:03d92e3e170bb629:[0, 1, 2]
//   sqrt       hand-authored
//   fracbar    hand-authored
//
// Each stroke is <=32 points, resampled (RDP simplify + uniform
// arclength), normalized into a unit box (larger dimension == 1.0,
// aspect preserved, origin at the glyph's top-left corner).

import CoreGraphics

let glyphStrokes: [String: [[CGPoint]]] = [
    "0": [
        [CGPoint(x: 0.2786, y: 0.0000), CGPoint(x: 0.1013, y: 0.2911), CGPoint(x: 0.0000, y: 0.5823), CGPoint(x: 0.0000, y: 0.8555), CGPoint(x: 0.0475, y: 0.9461), CGPoint(x: 0.1583, y: 0.9937), CGPoint(x: 0.3198, y: 1.0000), CGPoint(x: 0.3599, y: 0.9910), CGPoint(x: 0.4052, y: 0.9240), CGPoint(x: 0.4686, y: 0.6203), CGPoint(x: 0.4686, y: 0.2025), CGPoint(x: 0.4305, y: 0.1139), CGPoint(x: 0.3920, y: 0.0754), CGPoint(x: 0.3420, y: 0.0634)],
    ],
    "1": [
        [CGPoint(x: 0.1082, y: 0.8716), CGPoint(x: 0.0327, y: 0.8903), CGPoint(x: 0.0000, y: 0.7923), CGPoint(x: 0.0352, y: 0.4755), CGPoint(x: 0.1284, y: 0.0000), CGPoint(x: 0.1007, y: 0.0818), CGPoint(x: 0.0982, y: 0.1795), CGPoint(x: 0.1284, y: 0.4732), CGPoint(x: 0.1686, y: 0.6549), CGPoint(x: 0.2265, y: 0.8180), CGPoint(x: 0.2869, y: 0.9089), CGPoint(x: 0.4078, y: 1.0000)],
    ],
    "2": [
        [CGPoint(x: 0.1505, y: 0.3542), CGPoint(x: 0.1164, y: 0.3469), CGPoint(x: 0.0929, y: 0.2507), CGPoint(x: 0.1455, y: 0.0795), CGPoint(x: 0.2020, y: 0.0084), CGPoint(x: 0.2378, y: 0.0000), CGPoint(x: 0.2753, y: 0.0274), CGPoint(x: 0.3117, y: 0.0940), CGPoint(x: 0.3307, y: 0.1836), CGPoint(x: 0.3318, y: 0.3246), CGPoint(x: 0.2613, y: 0.7112), CGPoint(x: 0.2037, y: 0.8764), CGPoint(x: 0.1399, y: 0.9694), CGPoint(x: 0.0890, y: 1.0000), CGPoint(x: 0.0470, y: 0.9973), CGPoint(x: 0.0000, y: 0.9221), CGPoint(x: 0.0073, y: 0.8069), CGPoint(x: 0.0252, y: 0.7717), CGPoint(x: 0.0593, y: 0.7622), CGPoint(x: 0.1634, y: 0.8426), CGPoint(x: 0.2686, y: 0.9914), CGPoint(x: 0.2854, y: 0.9957), CGPoint(x: 0.3027, y: 0.9629)],
    ],
    "3": [
        [CGPoint(x: 0.0217, y: 0.1957), CGPoint(x: 0.0000, y: 0.1395), CGPoint(x: 0.0243, y: 0.1098), CGPoint(x: 0.1776, y: 0.0168), CGPoint(x: 0.3265, y: 0.0000), CGPoint(x: 0.4435, y: 0.0385), CGPoint(x: 0.4868, y: 0.1002), CGPoint(x: 0.4738, y: 0.2294), CGPoint(x: 0.3932, y: 0.4002), CGPoint(x: 0.2763, y: 0.5413), CGPoint(x: 0.3369, y: 0.5220), CGPoint(x: 0.4781, y: 0.5886), CGPoint(x: 0.5595, y: 0.6752), CGPoint(x: 0.5855, y: 0.7674), CGPoint(x: 0.5570, y: 0.8669), CGPoint(x: 0.4755, y: 0.9390), CGPoint(x: 0.3733, y: 0.9695), CGPoint(x: 0.0667, y: 1.0000)],
    ],
    "4": [
        [CGPoint(x: 0.4681, y: 0.0426), CGPoint(x: 0.0000, y: 0.6809), CGPoint(x: 0.7234, y: 0.6809)],
        [CGPoint(x: 0.5213, y: 0.0000), CGPoint(x: 0.5213, y: 1.0000)],
    ],
    "5": [
        [CGPoint(x: 0.8152, y: 0.0000), CGPoint(x: 0.0243, y: 0.0000), CGPoint(x: 0.0243, y: 0.4202)],
        [CGPoint(x: 0.0426, y: 0.5561), CGPoint(x: 0.0085, y: 0.6350), CGPoint(x: 0.0000, y: 0.7196), CGPoint(x: 0.0178, y: 0.8030), CGPoint(x: 0.0606, y: 0.8782), CGPoint(x: 0.1246, y: 0.9392), CGPoint(x: 0.2048, y: 0.9810), CGPoint(x: 0.2945, y: 1.0000), CGPoint(x: 0.3864, y: 0.9948), CGPoint(x: 0.4729, y: 0.9657), CGPoint(x: 0.5469, y: 0.9152), CGPoint(x: 0.6024, y: 0.8474), CGPoint(x: 0.6348, y: 0.7679), CGPoint(x: 0.6414, y: 0.6831), CGPoint(x: 0.6217, y: 0.6001), CGPoint(x: 0.5773, y: 0.5257), CGPoint(x: 0.5119, y: 0.4659), CGPoint(x: 0.4308, y: 0.4257)],
    ],
    "6": [
        [CGPoint(x: 0.3656, y: 0.0000), CGPoint(x: 0.2745, y: 0.0522), CGPoint(x: 0.2062, y: 0.1319), CGPoint(x: 0.1687, y: 0.2299), CGPoint(x: 0.1733, y: 0.3693), CGPoint(x: 0.5486, y: 0.6507), CGPoint(x: 0.5657, y: 0.7350), CGPoint(x: 0.5520, y: 0.8199), CGPoint(x: 0.5089, y: 0.8962), CGPoint(x: 0.4412, y: 0.9554), CGPoint(x: 0.3562, y: 0.9913), CGPoint(x: 0.2631, y: 1.0000), CGPoint(x: 0.1719, y: 0.9805), CGPoint(x: 0.0926, y: 0.9349), CGPoint(x: 0.0337, y: 0.8681), CGPoint(x: 0.0017, y: 0.7875), CGPoint(x: 0.0000, y: 0.7017), CGPoint(x: 0.0288, y: 0.6200), CGPoint(x: 0.0849, y: 0.5513), CGPoint(x: 0.1623, y: 0.5031), CGPoint(x: 0.2527, y: 0.4805), CGPoint(x: 0.3461, y: 0.4860), CGPoint(x: 0.4325, y: 0.5190), CGPoint(x: 0.5025, y: 0.5760), CGPoint(x: 0.5486, y: 0.6507)],
    ],
    "7": [
        [CGPoint(x: 0.0000, y: 0.0000), CGPoint(x: 0.8864, y: 0.0000), CGPoint(x: 0.2955, y: 1.0000)],
    ],
    "8": [
        [CGPoint(x: 0.3050, y: 0.4369), CGPoint(x: 0.2210, y: 0.4220), CGPoint(x: 0.1483, y: 0.3794), CGPoint(x: 0.0968, y: 0.3148), CGPoint(x: 0.0734, y: 0.2369), CGPoint(x: 0.0813, y: 0.1563), CGPoint(x: 0.1194, y: 0.0838), CGPoint(x: 0.1825, y: 0.0293), CGPoint(x: 0.2622, y: 0.0000), CGPoint(x: 0.3477, y: 0.0000), CGPoint(x: 0.4274, y: 0.0293), CGPoint(x: 0.4906, y: 0.0838), CGPoint(x: 0.5287, y: 0.1563), CGPoint(x: 0.5366, y: 0.2369), CGPoint(x: 0.5132, y: 0.3148), CGPoint(x: 0.4617, y: 0.3794), CGPoint(x: 0.3890, y: 0.4220), CGPoint(x: 0.3050, y: 0.4369)],
        [CGPoint(x: 0.3050, y: 1.0000), CGPoint(x: 0.2056, y: 0.9841), CGPoint(x: 0.1170, y: 0.9381), CGPoint(x: 0.0488, y: 0.8669), CGPoint(x: 0.0083, y: 0.7783), CGPoint(x: 0.0000, y: 0.6820), CGPoint(x: 0.0247, y: 0.5882), CGPoint(x: 0.0798, y: 0.5072), CGPoint(x: 0.1593, y: 0.4478), CGPoint(x: 0.2546, y: 0.4164), CGPoint(x: 0.3553, y: 0.4164), CGPoint(x: 0.4506, y: 0.4478), CGPoint(x: 0.5301, y: 0.5072), CGPoint(x: 0.5852, y: 0.5882), CGPoint(x: 0.6100, y: 0.6820), CGPoint(x: 0.6016, y: 0.7783), CGPoint(x: 0.5612, y: 0.8669), CGPoint(x: 0.4929, y: 0.9381), CGPoint(x: 0.4043, y: 0.9841), CGPoint(x: 0.3050, y: 1.0000)],
    ],
    "9": [
        [CGPoint(x: 0.4033, y: 0.5317), CGPoint(x: 0.2942, y: 0.5483), CGPoint(x: 0.1858, y: 0.5276), CGPoint(x: 0.0930, y: 0.4724), CGPoint(x: 0.0281, y: 0.3902), CGPoint(x: 0.0000, y: 0.2921), CGPoint(x: 0.0125, y: 0.1913), CGPoint(x: 0.0638, y: 0.1015), CGPoint(x: 0.1471, y: 0.0347), CGPoint(x: 0.2511, y: 0.0000), CGPoint(x: 0.3617, y: 0.0021), CGPoint(x: 0.4641, y: 0.0407), CGPoint(x: 0.5443, y: 0.1105), CGPoint(x: 0.5916, y: 0.2022), CGPoint(x: 0.5995, y: 0.3034), CGPoint(x: 0.5671, y: 0.4004), CGPoint(x: 0.4986, y: 0.4801), CGPoint(x: 0.4033, y: 0.5317)],
        [CGPoint(x: 0.5764, y: 0.2472), CGPoint(x: 0.4509, y: 1.0000)],
    ],
    "x": [
        [CGPoint(x: 0.0000, y: 0.0000), CGPoint(x: 0.8929, y: 1.0000)],
        [CGPoint(x: 0.8929, y: 0.0000), CGPoint(x: 0.0000, y: 1.0000)],
    ],
    "y": [
        [CGPoint(x: 0.0000, y: 0.0000), CGPoint(x: 0.4222, y: 0.5222)],
        [CGPoint(x: 0.8444, y: 0.0000), CGPoint(x: 0.4222, y: 0.5222), CGPoint(x: 0.2889, y: 1.0000)],
    ],
    "+": [
        [CGPoint(x: 0.3221, y: 0.0000), CGPoint(x: 0.3221, y: 0.1035), CGPoint(x: 0.2875, y: 0.2989), CGPoint(x: 0.2875, y: 1.0000)],
        [CGPoint(x: 0.0000, y: 0.6782), CGPoint(x: 0.0977, y: 0.6495), CGPoint(x: 0.1624, y: 0.6552), CGPoint(x: 0.3680, y: 0.6323), CGPoint(x: 0.5797, y: 0.6323)],
    ],
    "-": [
        [CGPoint(x: 0.0000, y: 0.0000), CGPoint(x: 1.0000, y: 0.0000)],
    ],
    "=": [
        [CGPoint(x: 0.0652, y: 0.1000), CGPoint(x: 0.0000, y: 0.0943), CGPoint(x: 0.2342, y: 0.0811), CGPoint(x: 0.5804, y: 0.0039), CGPoint(x: 0.6538, y: 0.0000), CGPoint(x: 0.7128, y: 0.0340)],
        [CGPoint(x: 0.2974, y: 0.4432), CGPoint(x: 0.3686, y: 0.4582), CGPoint(x: 0.4521, y: 0.4468), CGPoint(x: 0.7882, y: 0.3772), CGPoint(x: 1.0000, y: 0.3130)],
    ],
    "(": [
        [CGPoint(x: 0.4419, y: 0.0000), CGPoint(x: 0.3105, y: 0.1086), CGPoint(x: 0.1635, y: 0.3102), CGPoint(x: 0.0859, y: 0.4395), CGPoint(x: 0.0000, y: 0.7265), CGPoint(x: 0.0191, y: 0.8530), CGPoint(x: 0.0605, y: 0.8996), CGPoint(x: 0.1961, y: 0.9678), CGPoint(x: 0.4114, y: 1.0000)],
    ],
    ")": [
        [CGPoint(x: 0.1663, y: 0.0000), CGPoint(x: 0.1959, y: 0.3686), CGPoint(x: 0.1841, y: 0.5305), CGPoint(x: 0.1251, y: 0.7688), CGPoint(x: 0.0522, y: 0.9322), CGPoint(x: 0.0000, y: 1.0000)],
    ],
    ".": [
        [CGPoint(x: 0.9848, y: 0.5000), CGPoint(x: 0.8660, y: 0.8264), CGPoint(x: 0.5653, y: 1.0000), CGPoint(x: 0.2232, y: 0.9397), CGPoint(x: 0.0000, y: 0.6736), CGPoint(x: 0.0000, y: 0.3264), CGPoint(x: 0.2232, y: 0.0603), CGPoint(x: 0.5653, y: 0.0000), CGPoint(x: 0.8660, y: 0.1736), CGPoint(x: 0.9848, y: 0.5000)],
    ],
    "/": [
        [CGPoint(x: 0.1988, y: 0.0000), CGPoint(x: 0.1645, y: 0.2808), CGPoint(x: 0.0436, y: 0.9188), CGPoint(x: 0.0000, y: 1.0000)],
    ],
    "±": [
        [CGPoint(x: 0.3612, y: 0.0000), CGPoint(x: 0.3366, y: 0.0224), CGPoint(x: 0.3029, y: 0.1153), CGPoint(x: 0.2418, y: 0.3649), CGPoint(x: 0.2325, y: 0.4802), CGPoint(x: 0.2510, y: 0.5594)],
        [CGPoint(x: 0.0000, y: 0.4871), CGPoint(x: 0.0214, y: 0.4733), CGPoint(x: 0.3612, y: 0.4303)],
        [CGPoint(x: 0.0765, y: 0.9965), CGPoint(x: 0.0918, y: 1.0000), CGPoint(x: 0.2999, y: 0.9759), CGPoint(x: 0.4253, y: 0.9742)],
    ],
    "√": [
        [CGPoint(x: 0.0000, y: 0.4468), CGPoint(x: 0.1277, y: 0.6170), CGPoint(x: 0.3404, y: 0.0000), CGPoint(x: 1.0000, y: 0.0000)],
    ],
    "fracbar": [
        [CGPoint(x: 0.0000, y: 0.0000), CGPoint(x: 1.0000, y: 0.0000)],
    ],
]
